// <auto-generated />
using System;
using EC.CRM.Backend.Persistence.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EC.CRM.Backend.Persistence.Migrations
{
    [DbContext(typeof(EngineeringClubDbContext))]
    [Migration("20240212181720_UpdateDefaultValues")]
    partial class UpdateDefaultValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("9132b8a0-071c-467f-a146-becf9256dde4"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserInfoUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Uid");

                    b.HasIndex("UserInfoUid");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("6fce367f-9c02-4b7e-9604-6f0004afd83f"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Uid");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserInfoUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoUid")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("940c8245-661d-4d10-b948-a5edbe18dee4"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Uid");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.State", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("14f705dc-a2af-437e-88a2-c6b6a90c1d2a"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.ToTable("States");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.Property<Guid>("StateUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserInfoUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("StateUid");

                    b.HasIndex("UserInfoUid")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.UserInfo", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("73f8447e-8b35-4f32-adac-9fe9876529cf"));

                    b.Property<decimal?>("CurentSalary")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LocationUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Paid")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("RoleUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Uid");

                    b.HasIndex("LocationUid");

                    b.HasIndex("RoleUid");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Job", b =>
                {
                    b.HasOne("EC.CRM.Backend.Domain.Entities.UserInfo", "UserInfo")
                        .WithMany("Jobs")
                        .HasForeignKey("UserInfoUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Mentor", b =>
                {
                    b.HasOne("EC.CRM.Backend.Domain.Entities.UserInfo", "UserInfo")
                        .WithOne("MentorProperties")
                        .HasForeignKey("EC.CRM.Backend.Domain.Entities.Mentor", "UserInfoUid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Student", b =>
                {
                    b.HasOne("EC.CRM.Backend.Domain.Entities.Mentor", "Mentor")
                        .WithMany("Students")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EC.CRM.Backend.Domain.Entities.State", "State")
                        .WithMany("Students")
                        .HasForeignKey("StateUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EC.CRM.Backend.Domain.Entities.UserInfo", "UserInfo")
                        .WithOne("StudentProperties")
                        .HasForeignKey("EC.CRM.Backend.Domain.Entities.Student", "UserInfoUid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("State");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.UserInfo", b =>
                {
                    b.HasOne("EC.CRM.Backend.Domain.Entities.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationUid");

                    b.HasOne("EC.CRM.Backend.Domain.Entities.Role", "Role")
                        .WithMany("UserInfos")
                        .HasForeignKey("RoleUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Location", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Mentor", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserInfos");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.State", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EC.CRM.Backend.Domain.Entities.UserInfo", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("MentorProperties");

                    b.Navigation("StudentProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
